### ISSUE TITLE
Possible to add ips ? 

### ISSUE THREAD

**Issue by GoRiLliAz** [Ilusion9/sm-list-disconnections#1]
hi

Possible to add ips with steamid and pseudo ? 

Thanks

**Comment by GoRiLliAz** [comment]
@Ilusion9 ?

**Comment by Ilusion9** [comment]
What is pseudo?
I will put player's ips in a new version.

**Comment by GoRiLliAz** [comment]
pseudo in french = player nick name
But my title is wrong just add ips
Thanks

**Comment by Ilusion9** [comment]
The plugin was updated.
